name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "Test"
      - name: Build
        run: echo "Build"
      - name: Build 2
        run: echo "Build2"
